# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending Approval'),
                    ('ENROLLED', 'Enrolled'),
                    ('REJECTED', 'Rejected'),
                    ('DROPPED', 'Dropped'),
                    ('CANCELLED', 'Cancelled'),
                    ('WAITLISTED', 'Waitlisted'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
