# Generated by Django 6.0.2 on 2026-05-23 15:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_expand_enrollment_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_student_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('student_number'), condition=models.Q(('student_number__isnull', False)), name='unique_student_number_ci'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('middle_name'), django.db.models.functions.text.Lower('last_name'), name='unique_student_full_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_ci'),
        ),
    ]
