# Generated by Django 6.0.3 on 2026-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_student_unique_student_email_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
